import 'package:tiptop_game_engine/core/services/registry_data_part1.dart';

List<AssetLibraryInfo> getRegistryPart2() {
  return [
    // ==========================================
    // 🔊 АУДИО, МУЗИКА & SFX (51-70)
    // ==========================================
    AssetLibraryInfo(
      id: 'freesound',
      name: 'FreeSound.org Universal Archive',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '580,000+ звука',
      countNumber: 580000,
      license: 'CC0 / CC-BY',
      description: 'Най-голямата звукова база данни в света: стъпки, експлозии, лазери, вятър.',
      url: 'https://freesound.org',
      tags: ['sfx', 'foley', 'explosions', 'ambience'],
    ),
    AssetLibraryInfo(
      id: 'incompetech',
      name: 'Incompetech (Kevin MacLeod)',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '2,200+ саундтрака',
      countNumber: 2200,
      license: 'CC-BY',
      description: 'Легендарните гейм саундтраци за екшън, фентъзи, приключения и ужаси.',
      url: 'https://incompetech.com',
      tags: ['soundtracks', 'kevin macleod', 'orchestral'],
    ),
    AssetLibraryInfo(
      id: 'sonniss_gdc',
      name: 'Sonniss GDC Pro Archive',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '45+ GB студийни звуци',
      countNumber: 35000,
      license: 'Royalty-Free Commercial',
      description: 'Студийни записи от водещи звукови дизайнери, пускани ежегодно за разработчици.',
      url: 'https://sonniss.com/gameaudioarchive',
      tags: ['hollywood sfx', 'weapons', 'magic'],
    ),
    AssetLibraryInfo(
      id: 'bensound',
      name: 'Bensound Free Cinematic',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '850+ трака',
      countNumber: 850,
      license: 'Free with Attribution',
      description: 'Епична рок, електронна и кинематографична фонова музика.',
      url: 'https://bensound.com',
      tags: ['cinematic', 'epic', 'action'],
    ),
    AssetLibraryInfo(
      id: 'kenney_audio',
      name: 'Kenney Audio Pack',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '4,900+ звука',
      countNumber: 4900,
      license: 'CC0 Public Domain',
      description: 'Звуци за скачане, събиране на монети, бутони, стрелба и интерфейс.',
      url: 'https://kenney.nl',
      tags: ['ui clicks', 'jumps', 'coins', 'retro sfx'],
    ),
    AssetLibraryInfo(
      id: 'free_music_archive',
      name: 'Free Music Archive (FMA)',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '150,000+ песни',
      countNumber: 150000,
      license: 'Creative Commons',
      description: 'Отворена независима музика с жанрови филтри за нива.',
      url: 'https://freemusicarchive.org',
      tags: ['music', 'electronic', 'ambient'],
    ),
    AssetLibraryInfo(
      id: 'chosic',
      name: 'Chosic Mood Game Music',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '10,000+ трака',
      countNumber: 10000,
      license: 'CC0 / CC-BY',
      description: 'Търсачка за музика по настроение: битка с бос, киберпънк, спокойствие.',
      url: 'https://chosic.com',
      tags: ['mood search', 'boss battle', 'bgm'],
    ),
    AssetLibraryInfo(
      id: 'game_sounds_xyz',
      name: 'GameSounds.xyz Collections',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '35+ GB аудио',
      countNumber: 25000,
      license: 'Open Access',
      description: 'Директни пакети със звукови ефекти за игри.',
      url: 'https://gamesounds.xyz',
      tags: ['archive', 'sfx kits'],
    ),
    AssetLibraryInfo(
      id: 'zapsplat',
      name: 'ZapSplat Free Tier',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '70,000+ звука',
      countNumber: 70000,
      license: 'Free Standard',
      description: 'Професионални звуци за удари, мечове, стъпки и чудовища.',
      url: 'https://zapsplat.com',
      tags: ['footsteps', 'swords', 'creatures'],
    ),
    AssetLibraryInfo(
      id: 'soundbible',
      name: 'SoundBible Free WAVs',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '2,500+ звука',
      countNumber: 2500,
      license: 'Public Domain / CC',
      description: 'Звуци за гръмотевици, сирени, пистолети и звънци.',
      url: 'https://soundbible.com',
      tags: ['wav', 'guns', 'thunder'],
    ),
    AssetLibraryInfo(
      id: 'ninety_nine_sounds',
      name: '99Sounds Sound Design Kits',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '35+ албума',
      countNumber: 3500,
      license: '100% Royalty Free',
      description: 'Тъмни дронове, киберпънк ефекти, филмов саунд дизайн.',
      url: 'https://99sounds.org',
      tags: ['sound design', 'cyberpunk', 'drones'],
    ),
    AssetLibraryInfo(
      id: 'audionautix',
      name: 'Audionautix (Jason Shaw)',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '1,500+ трака',
      countNumber: 1500,
      license: 'CC-BY 4.0',
      description: 'Акустична и енергична екшън музика.',
      url: 'https://audionautix.com',
      tags: ['acoustic', 'energy', 'action'],
    ),
    AssetLibraryInfo(
      id: 'silverman_sound',
      name: 'Silverman Sound Studios',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '400+ трака',
      countNumber: 400,
      license: 'CC-BY',
      description: 'Синтуейв и модерни епични композиции.',
      url: 'https://silvermansound.com',
      tags: ['synthwave', 'modern epic'],
    ),
    AssetLibraryInfo(
      id: 'musopen',
      name: 'Musopen Public Orchestra',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '12,000+ записа',
      countNumber: 12000,
      license: 'Public Domain',
      description: 'Истински оркестрови записи на класическа музика (Бетовен, Моцарт, Бах).',
      url: 'https://musopen.org',
      tags: ['classical', 'orchestra', 'epic'],
    ),
    AssetLibraryInfo(
      id: 'pacdv',
      name: 'PacDV Sound Effects',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '500+ звука',
      countNumber: 500,
      license: 'Free Commercial',
      description: 'Механични звуци, мотори, шапки, врати.',
      url: 'https://pacdv.com/sounds',
      tags: ['mechanical', 'engines'],
    ),
    AssetLibraryInfo(
      id: 'bbc_sound',
      name: 'BBC Sound Effects Archive',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '33,000+ звука',
      countNumber: 33000,
      license: 'Non-Commercial / Research',
      description: 'Исторически и природни записи от цялата планета.',
      url: 'https://sound-effects.bbcrewind.co.uk',
      tags: ['nature', 'world', 'historical'],
    ),
    AssetLibraryInfo(
      id: 'looperman',
      name: 'Looperman Free Loops & Beats',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '200,000+ лупа',
      countNumber: 200000,
      license: 'Free Royalty-Free',
      description: 'Ритмични секвенции за фонови бийтове в игри.',
      url: 'https://looperman.com',
      tags: ['beats', 'loops', 'drums'],
    ),
    AssetLibraryInfo(
      id: 'free_music_wave',
      name: 'Free Music Wave NoCopyright',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '1,200+ трака',
      countNumber: 1200,
      license: 'No Copyright',
      description: 'Модерна EDM и киберпънк музика.',
      url: 'https://youtube.com',
      tags: ['edm', 'cyberpunk', 'electronic'],
    ),
    AssetLibraryInfo(
      id: 'opengameart_music',
      name: 'OpenGameArt Music Archive',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '6,500+ парчета',
      countNumber: 6500,
      license: 'CC0 / CC-BY',
      description: 'Оркестрални и 8-битови тракове за нива.',
      url: 'https://opengameart.org',
      tags: ['chiptune', 'level music'],
    ),
    AssetLibraryInfo(
      id: 'youtube_audio_free',
      name: 'YouTube Audio Library (No Attribution)',
      category: '🔊 Аудио, Музика & SFX',
      exactCount: '2,000+ трака',
      countNumber: 2000,
      license: 'YouTube Free License',
      description: 'Одобрени за игри фонови инструментални парчета.',
      url: 'https://studio.youtube.com',
      tags: ['background', 'instrumentals'],
    ),

    // ==========================================
    // 🏃 АНИМАЦИИ & MOCAP (71-80)
    // ==========================================
    AssetLibraryInfo(
      id: 'mixamo',
      name: 'Adobe Mixamo Motion Library',
      category: '🏃 Анимации & MoCap',
      exactCount: '2,488 движения',
      countNumber: 2488,
      license: 'Royalty-Free Commercial',
      description: 'Златният индустриален стандарт за бягане, скокове, танци, бой и умиране.',
      url: 'https://mixamo.com',
      tags: ['locomotion', 'combat', 'dance', 'humanoid'],
    ),
    AssetLibraryInfo(
      id: 'cmu_mocap',
      name: 'CMU Graphics Lab MoCap Database',
      category: '🏃 Анимации & MoCap',
      exactCount: '2,605 сесии',
      countNumber: 2605,
      license: 'Public Domain',
      description: 'Оптичен MoCap архив от Carnegie Mellon University с реални актьори.',
      url: 'http://mocap.cs.cmu.edu',
      tags: ['optical mocap', 'real human', 'athletic'],
    ),
    AssetLibraryInfo(
      id: 'actorcore',
      name: 'Reallusion ActorCore Free Tier',
      category: '🏃 Анимации & MoCap',
      exactCount: '1,850 движения',
      countNumber: 1850,
      license: 'Pro MoCap Free Tier',
      description: 'AAA каскади, бойни изкуства с катана, тактическа стрелба.',
      url: 'https://actorcore.reallusion.com',
      tags: ['stunts', 'martial arts', 'sword'],
    ),
    AssetLibraryInfo(
      id: 'bandai_namco',
      name: 'Bandai Namco Research MoCap',
      category: '🏃 Анимации & MoCap',
      exactCount: '1,500+ движения',
      countNumber: 1500,
      license: 'Research Open Dataset',
      description: 'Бойни аниме комбота, нинджа акробатика и екшън пози.',
      url: 'https://github.com/BandaiNamcoResearchInc',
      tags: ['anime', 'action', 'combos', 'fight'],
    ),
    AssetLibraryInfo(
      id: 'unity_mocap',
      name: 'Unity Asset Store Free MoCap',
      category: '🏃 Анимации & MoCap',
      exactCount: '1,200+ движения',
      countNumber: 1200,
      license: 'Unity Free Assets',
      description: 'Стандартни хуманоидни анимации за катерене, плуване и ходене.',
      url: 'https://assetstore.unity.com',
      tags: ['humanoid', 'retargeting'],
    ),
    AssetLibraryInfo(
      id: 'sfu_motion',
      name: 'SFU Motion Capture Lab',
      category: '🏃 Анимации & MoCap',
      exactCount: '820 записа',
      countNumber: 820,
      license: 'Open Academic',
      description: 'Сценични танци, емоции, жестомимика, театрални движения.',
      url: 'https://mocap.cs.sfu.ca',
      tags: ['acting', 'emotes', 'dances'],
    ),
    AssetLibraryInfo(
      id: 'accad_mocap',
      name: 'ACCAD Ohio State MoCap',
      category: '🏃 Анимации & MoCap',
      exactCount: '650 записа',
      countNumber: 650,
      license: 'Academic Free',
      description: 'Спортни и атлетични движения, бягане с препятствия.',
      url: 'https://accad.osu.edu',
      tags: ['sports', 'hurdles', 'jumping'],
    ),
    AssetLibraryInfo(
      id: 'hdm05_mocap',
      name: 'HDM05 Bonn University MoCap',
      category: '🏃 Анимации & MoCap',
      exactCount: '1,500 клипа',
      countNumber: 1500,
      license: 'Open Access',
      description: 'Детайлни гимнастически упражнения и бойни пози.',
      url: 'http://resources.mpi-inf.mpg.de/HDM05',
      tags: ['gymnastics', 'exercises'],
    ),
    AssetLibraryInfo(
      id: 'kit_mocap',
      name: 'KIT Whole-Body Motion Database',
      category: '🏃 Анимации & MoCap',
      exactCount: '4,000+ движения',
      countNumber: 4000,
      license: 'Open Research',
      description: 'База данни за роботика и двукраки хуманоидни манекени.',
      url: 'https://motion-database.humanoids.kit.edu',
      tags: ['robotics', 'bipedal', 'kinematics'],
    ),
    AssetLibraryInfo(
      id: 'eyes_japan',
      name: 'Eyes, Japan MoCap Collection',
      category: '🏃 Анимации & MoCap',
      exactCount: '1,200 движения',
      countNumber: 1200,
      license: 'Open Source',
      description: 'Традиционни японски бойни стилове и ежедневни жестове.',
      url: 'http://mocapdata.com',
      tags: ['japanese martial arts', 'gestures'],
    ),

    // ==========================================
    // ⚡ ШЕЙДЪРИ & VFX (81-87)
    // ==========================================
    AssetLibraryInfo(
      id: 'godot_shaders',
      name: 'GodotShaders.com Universal Hub',
      category: '⚡ Шейдъри & VFX',
      exactCount: '1,450+ шейдъра',
      countNumber: 1450,
      license: 'CC0 / MIT',
      description: 'Шейдъри за вряща лава, вода, мъгла, дисоциация, вятър, неон, разпадане.',
      url: 'https://godotshaders.com',
      tags: ['godot shaders', 'lava', 'water', 'dissolve'],
    ),
    AssetLibraryInfo(
      id: 'shadertoy',
      name: 'Shadertoy Open GLSL Archive',
      category: '⚡ Шейдъри & VFX',
      exactCount: '50,000+ кода',
      countNumber: 50000,
      license: 'Creative Commons',
      description: 'Фрагментни математически шейдъри за фрактали, звезди, пламъци и кристали.',
      url: 'https://shadertoy.com',
      tags: ['glsl', 'procedural', 'raymarching'],
    ),
    AssetLibraryInfo(
      id: 'glsl_sandbox',
      name: 'GLSL Sandbox Gallery',
      category: '⚡ Шейдъри & VFX',
      exactCount: '20,000+ шейдъра',
      countNumber: 20000,
      license: 'Open Source',
      description: 'Отворени светлинни и оптични ефекти в реално време.',
      url: 'https://glslsandbox.com',
      tags: ['sandbox', 'fx'],
    ),
    AssetLibraryInfo(
      id: 'book_of_shaders',
      name: 'The Book of Shaders Gallery',
      category: '⚡ Шейдъри & VFX',
      exactCount: '100+ алгоритъма',
      countNumber: 100,
      license: 'MIT',
      description: 'Фундаментални шейдъри за генериране на релефи, шум на Перлин и магии.',
      url: 'https://thebookofshaders.com',
      tags: ['noise', 'perlin', 'math'],
    ),
    AssetLibraryInfo(
      id: 'filament_materials',
      name: 'Filament PBR Sample Materials',
      category: '⚡ Шейдъри & VFX',
      exactCount: '50+ PBR шейдъра',
      countNumber: 50,
      license: 'Apache 2.0 (Google)',
      description: 'Официални високотехнологични материали на Google Filament (метал, стъкло).',
      url: 'https://github.com/google/filament',
      tags: ['google filament', 'pbr materials'],
    ),
    AssetLibraryInfo(
      id: 'unity_shadergraph_open',
      name: 'Unity Shader Graph Open Repo',
      category: '⚡ Шейдъри & VFX',
      exactCount: '350+ шейдъра',
      countNumber: 350,
      license: 'MIT',
      description: 'Визуални шейдъри, лесно преносими в код.',
      url: 'https://github.com/keijiro',
      tags: ['visual shaders', 'vfx'],
    ),
    AssetLibraryInfo(
      id: 'kenney_particle_pack',
      name: 'Kenney Particle Pack',
      category: '⚡ Шейдъри & VFX',
      exactCount: '100+ текстури',
      countNumber: 100,
      license: 'CC0 Public Domain',
      description: 'Текстури за дим, огън, искри, експлозии и портали.',
      url: 'https://kenney.nl',
      tags: ['smoke', 'fire', 'sparks', 'particles'],
    ),

    // ==========================================
    // 📱 UI, HUD & ШРИФТОВЕ (88-94)
    // ==========================================
    AssetLibraryInfo(
      id: 'kenney_ui',
      name: 'Kenney UI Master Pack',
      category: '📱 UI, HUD & Шрифтове',
      exactCount: '1,500+ елемента',
      countNumber: 1500,
      license: 'CC0 Public Domain',
      description: 'Векторни бутони, плъзгачи, панели, диалози и геймпад контролери.',
      url: 'https://kenney.nl',
      tags: ['ui', 'buttons', 'gamepad icons'],
    ),
    AssetLibraryInfo(
      id: 'free_game_gui',
      name: 'FreeGameGUI Kits',
      category: '📱 UI, HUD & Шрифтове',
      exactCount: '450+ HUD кита',
      countNumber: 450,
      license: 'Free Commercial',
      description: 'Фентъзи RPG и Sci-Fi интерфейси, кръвни ленти, мини-карти.',
      url: 'https://freegamegui.com',
      tags: ['hud', 'healthbars', 'minimap'],
    ),
    AssetLibraryInfo(
      id: 'opengameart_gui',
      name: 'OpenGameArt GUI Archive',
      category: '📱 UI, HUD & Шрифтове',
      exactCount: '2,100+ елемента',
      countNumber: 2100,
      license: 'CC0 / GPL',
      description: 'Инвентарни решетки, кутии за предмети, стрелки и диалози.',
      url: 'https://opengameart.org',
      tags: ['inventory', 'boxes', 'dialogs'],
    ),
    AssetLibraryInfo(
      id: 'craftpix_ui',
      name: 'CraftPix UI & Badges',
      category: '📱 UI, HUD & Шрифтове',
      exactCount: '1,200+ икони',
      countNumber: 1200,
      license: 'Free License',
      description: 'Оценки за нива със звезди, кристали, заключени катинари.',
      url: 'https://craftpix.net',
      tags: ['stars', 'gems', 'level select'],
    ),
    AssetLibraryInfo(
      id: 'google_fonts_games',
      name: 'Google Fonts for Games',
      category: '📱 UI, HUD & Шрифтове',
      exactCount: '1,500+ шрифта',
      countNumber: 1500,
      license: 'SIL Open Font License',
      description: 'Пълен набор от отворени шрифтове за всички езици на кирилица и латиница.',
      url: 'https://fonts.google.com',
      tags: ['typography', 'fonts', 'cyrillic'],
    ),
    AssetLibraryInfo(
      id: 'dafont_free_arcade',
      name: 'DaFont 100% Free Arcade Fonts',
      category: '📱 UI, HUD & Шрифтове',
      exactCount: '800+ шрифта',
      countNumber: 800,
      license: '100% Free',
      description: 'Ретро пиксел и аркадни шрифтове за скор табла.',
      url: 'https://dafont.com',
      tags: ['pixel font', 'arcade', 'score'],
    ),
    AssetLibraryInfo(
      id: 'ui8_freebies',
      name: 'UI8 Gaming Freebies',
      category: '📱 UI, HUD & Шрифтове',
      exactCount: '120+ дизайна',
      countNumber: 120,
      license: 'Free Tier',
      description: 'Модерни минималистични интерфейси за мобилни игри.',
      url: 'https://ui8.net',
      tags: ['mobile ui', 'clean design'],
    ),

    // ==========================================
    // 🏛️ МУЗЕИ & НАСЛЕДСТВО (95-98)
    // ==========================================
    AssetLibraryInfo(
      id: 'british_museum',
      name: 'The British Museum 3D Archive',
      category: '🏛️ Музеи & Наследство',
      exactCount: '300+ скана',
      countNumber: 300,
      license: 'CC-BY-NC-SA',
      description: 'Мумии, розетският камък, древноегипетски и гръцки статуи.',
      url: 'https://sketchfab.com/britishmuseum',
      tags: ['mummy', 'egypt', 'sculptures', 'heritage'],
    ),
    AssetLibraryInfo(
      id: 'open_heritage_3d',
      name: 'Open Heritage 3D (CyArk / Google Arts)',
      category: '🏛️ Музеи & Наследство',
      exactCount: '120+ археологически обекта',
      countNumber: 120,
      license: 'Open Access Research',
      description: 'Лазерно сканирани цели древни градове, пирамиди и храмове.',
      url: 'https://openheritage3d.org',
      tags: ['temples', 'pyramids', 'ruins'],
    ),
    AssetLibraryInfo(
      id: 'scan_the_world',
      name: 'Scan The World (MyMiniFactory)',
      category: '🏛️ Музеи & Наследство',
      exactCount: '20,000+ скулптури',
      countNumber: 20000,
      license: 'CC0 / Open Access',
      description: 'Световни музейни произведения на изкуството от Лувъра, Ватикана и Метрополитън.',
      url: 'https://myminifactory.com/scantheworld',
      tags: ['statues', 'art', 'renaissance'],
    ),
    AssetLibraryInfo(
      id: 'sketchfab_heritage',
      name: 'Sketchfab Cultural Heritage Open Access',
      category: '🏛️ Музеи & Наследство',
      exactCount: '15,000+ скана',
      countNumber: 15000,
      license: 'CC0 Public Domain',
      description: 'Световни съкровища под официален свободен лиценз.',
      url: 'https://sketchfab.com',
      tags: ['artifacts', 'castles', 'fossils'],
    ),

    // ==========================================
    // 🗺️ РЕАЛНИ ТЕРЕНИ & КАРТИ (99-101)
    // ==========================================
    AssetLibraryInfo(
      id: 'openstreetmap_3d',
      name: 'OpenStreetMap 3D (OSM)',
      category: '🗺️ Реални Терени & Карти',
      exactCount: 'Цялата планета Земя',
      countNumber: 100000,
      license: 'ODbL / Open Data',
      description: 'Реални 3D контури на улици и сгради от всеки реален град по света (Париж, Ню Йорк, София).',
      url: 'https://openstreetmap.org',
      tags: ['real world', 'buildings', 'roads', 'gps'],
    ),
    AssetLibraryInfo(
      id: 'usgs_earth_explorer',
      name: 'USGS Earth Explorer / NASA SRTM',
      category: '🗺️ Реални Терени & Карти',
      exactCount: 'Глобален релеф',
      countNumber: 50000,
      license: 'Public Domain',
      description: 'Реални спътникови височинни карти (Heightmaps) за планини, каньони и вулкани.',
      url: 'https://earthexplorer.usgs.gov',
      tags: ['heightmaps', 'mountains', 'topography'],
    ),
    AssetLibraryInfo(
      id: 'tangram_heightmaps',
      name: 'Tangram Heightmapper Open Generator',
      category: '🗺️ Реални Терени & Карти',
      exactCount: 'Глобален генератор',
      countNumber: 25000,
      license: 'MIT / Open Source',
      description: 'Мигновено изтегляне на топографски карти за генериране на 3D релефи.',
      url: 'https://tangrams.github.io/heightmapper',
      tags: ['terrain generator', 'elevation'],
    ),
  ];
}
