class AssetLibraryInfo {
  final String id;
  final String name;
  final String category;
  final String exactCount;
  final int countNumber;
  final String license;
  final String description;
  final String url;
  final List<String> tags;

  AssetLibraryInfo({
    required this.id,
    required this.name,
    required this.category,
    required this.exactCount,
    required this.countNumber,
    required this.license,
    required this.description,
    required this.url,
    required this.tags,
  });
}

List<AssetLibraryInfo> getRegistryPart1() {
  return [
    // ==========================================
    // 🎲 3D МОДЕЛИ, МЕХОВЕ & СВЕТОВЕ (1-23)
    // ==========================================
    AssetLibraryInfo(
      id: 'poly_pizza',
      name: 'Poly Pizza (Google Poly Archive)',
      category: '🎲 3D Модели & Светове',
      exactCount: '4,500+ .glb',
      countNumber: 4500,
      license: 'CC0 / CC-BY',
      description: 'Огромен архив от нискополигонални 3D обекти с директен свободен CDN.',
      url: 'https://poly.pizza',
      tags: ['lowpoly', 'google poly', 'glb', 'weapons', 'props'],
    ),
    AssetLibraryInfo(
      id: 'kenney_3d',
      name: 'Kenney.nl 3D Assets',
      category: '🎲 3D Модели & Светове',
      exactCount: '1,800+ .glb',
      countNumber: 1800,
      license: 'CC0 Public Domain',
      description: 'Модулни градове, автомобили, космически кораби, подземия и замъци.',
      url: 'https://kenney.nl',
      tags: ['cars', 'city', 'space', 'dungeon', 'modular'],
    ),
    AssetLibraryInfo(
      id: 'quaternius',
      name: 'Quaternius Modular 3D',
      category: '🎲 3D Модели & Светове',
      exactCount: '1,650+ .glb',
      countNumber: 1650,
      license: 'CC0 Public Domain',
      description: 'Модулни роботи, ригнати герои, средновековни крепости и танкове.',
      url: 'https://quaternius.com',
      tags: ['characters', 'mechs', 'monsters', 'medieval', 'rigged'],
    ),
    AssetLibraryInfo(
      id: 'kay_lousberg',
      name: 'Kay Lousberg Game Kits',
      category: '🎲 3D Модели & Светове',
      exactCount: '950+ .glb',
      countNumber: 950,
      license: 'CC0 Public Domain',
      description: 'Модулни подземия с капани, скелети, съкровища и космически станции.',
      url: 'https://kaylousberg.com',
      tags: ['dungeon', 'chests', 'skeletons', 'modular kit'],
    ),
    AssetLibraryInfo(
      id: 'nasa_3d',
      name: 'NASA 3D Resources',
      category: '🎲 3D Модели & Светове',
      exactCount: '450+ модела',
      countNumber: 450,
      license: 'Public Domain',
      description: 'Истински 3D совалки, Марсоходи (Curiosity/Perseverance), МКС и планети.',
      url: 'https://nasa3d.arc.nasa.gov',
      tags: ['space', 'nasa', 'shuttle', 'rover', 'satellites'],
    ),
    AssetLibraryInfo(
      id: 'smithsonian_3d',
      name: 'Smithsonian 3D Digitization',
      category: '🎲 3D Модели & Светове',
      exactCount: '3,200+ скана',
      countNumber: 3200,
      license: 'CC0 Public Domain',
      description: 'Лазерно сканирани динозаври (T-Rex), мамути, исторически оръжия и статуи.',
      url: 'https://3d.si.edu',
      tags: ['dinosaurs', 'fossils', 'museum', 'scanned'],
    ),
    AssetLibraryInfo(
      id: 'sketchfab_free',
      name: 'Sketchfab Free Open Access',
      category: '🎲 3D Модели & Светове',
      exactCount: '500,000+ модела',
      countNumber: 500000,
      license: 'CC-BY / CC0',
      description: 'Най-голямата общност за фотореалистични PBR модели в света.',
      url: 'https://sketchfab.com',
      tags: ['pbr', 'realistic', 'vehicles', 'sculptures'],
    ),
    AssetLibraryInfo(
      id: 'opengameart_3d',
      name: 'OpenGameArt 3D Models',
      category: '🎲 3D Модели & Светове',
      exactCount: '4,800+ модела',
      countNumber: 4800,
      license: 'GPL / CC0',
      description: 'Отворен глобален архив от гейм разработчици за обекти и анимации.',
      url: 'https://opengameart.org',
      tags: ['community', 'fantasy', 'sci-fi'],
    ),
    AssetLibraryInfo(
      id: 'khronos_gltf',
      name: 'Khronos glTF Sample Models',
      category: '🎲 3D Модели & Светове',
      exactCount: '120+ PBR модела',
      countNumber: 120,
      license: 'Apache 2.0 / CC0',
      description: 'Еталонни модели с усъвършенствани материали (Transmission, Clearcoat).',
      url: 'https://github.com/KhronosGroup/glTF-Sample-Models',
      tags: ['gltf', 'pbr reference', 'shaders'],
    ),
    AssetLibraryInfo(
      id: 'pmndrs_market',
      name: 'PMNDRS Market',
      category: '🎲 3D Модели & Светове',
      exactCount: '350+ .glb',
      countNumber: 350,
      license: 'CC0 Public Domain',
      description: 'Модерни low-poly и PBR активи за рендеринг в реално време.',
      url: 'https://market.pmnd.rs',
      tags: ['three.js', 'stylized', 'modern'],
    ),
    AssetLibraryInfo(
      id: 'blendswap',
      name: 'Blend Swap Open Meshes',
      category: '🎲 3D Модели & Светове',
      exactCount: '25,000+ модела',
      countNumber: 25000,
      license: 'CC0 / CC-BY',
      description: 'Огромна база от готови Blender обекти, архитектура и персонажи.',
      url: 'https://blendswap.com',
      tags: ['blender', 'scenes', 'rigs'],
    ),
    AssetLibraryInfo(
      id: 'free3d',
      name: 'Free3D Asset Hub',
      category: '🎲 3D Модели & Светове',
      exactCount: '18,000+ модела',
      countNumber: 1800,
      license: 'Free Commercial Tier',
      description: '3D автомобили, оръжия, сгради и спортни съоръжения.',
      url: 'https://free3d.com',
      tags: ['cars', 'guns', 'architecture'],
    ),
    AssetLibraryInfo(
      id: 'cgtrader_free',
      name: 'CGTrader Free 3D Models',
      category: '🎲 3D Модели & Светове',
      exactCount: '40,000+ модела',
      countNumber: 40000,
      license: 'Royalty-Free Open',
      description: 'Професионален пазар за висококачествени студийни обекти.',
      url: 'https://cgtrader.com',
      tags: ['professional', 'interior', 'props'],
    ),
    AssetLibraryInfo(
      id: 'turbosquid_free',
      name: 'TurboSquid Free Collection',
      category: '🎲 3D Модели & Светове',
      exactCount: '6,000+ модела',
      countNumber: 6000,
      license: 'Free Tier License',
      description: 'Холивудско качество детайлни геометрии.',
      url: 'https://turbosquid.com',
      tags: ['highpoly', 'cinematic'],
    ),
    AssetLibraryInfo(
      id: 'clara_io',
      name: 'Clara.io WebGL Models',
      category: '🎲 3D Модели & Светове',
      exactCount: '10,000+ модела',
      countNumber: 10000,
      license: 'Creative Commons',
      description: 'Уеб-оптимизирани мрежи за бързо зареждане.',
      url: 'https://clara.io',
      tags: ['webgl', 'lightweight'],
    ),
    AssetLibraryInfo(
      id: 'nih_3d',
      name: 'NIH 3D Health & Biology',
      category: '🎲 3D Модели & Светове',
      exactCount: '12,000+ модела',
      countNumber: 12000,
      license: 'Public Domain',
      description: 'Анатомични скелети, кости, вируси, лабораторно оборудване.',
      url: 'https://3dprint.nih.gov',
      tags: ['skeleton', 'anatomy', 'medical'],
    ),
    AssetLibraryInfo(
      id: 'thingiverse_open',
      name: 'Thingiverse Open Meshes',
      category: '🎲 3D Модели & Светове',
      exactCount: '1,000,000+ STL/OBJ',
      countNumber: 1000000,
      license: 'Creative Commons',
      description: 'Механични роботи, зъбни предавки, дронове.',
      url: 'https://thingiverse.com',
      tags: ['robotics', 'parts', 'gears'],
    ),
    AssetLibraryInfo(
      id: 'printables_open',
      name: 'Printables 3D Database',
      category: '🎲 3D Модели & Светове',
      exactCount: '300,000+ модела',
      countNumber: 300000,
      license: 'Open Source',
      description: 'Модерни инженерни и гейминг фигури.',
      url: 'https://printables.com',
      tags: ['miniatures', 'props'],
    ),
    AssetLibraryInfo(
      id: 'ready_player_me',
      name: 'Ready Player Me Avatars',
      category: '🎲 3D Модели & Светове',
      exactCount: 'Безкраен генератор',
      countNumber: 50000,
      license: 'Free API Access',
      description: 'Генератор на напълно ригнати хуманоидни герои със стандартни кости.',
      url: 'https://readyplayer.me',
      tags: ['avatars', 'characters', 'clothes'],
    ),
    AssetLibraryInfo(
      id: 'microsoft_open_3d',
      name: 'Microsoft 3D Open Samples',
      category: '🎲 3D Модели & Светове',
      exactCount: '250+ модела',
      countNumber: 250,
      license: 'MIT / Open',
      description: 'Официални холографски и VR/AR примери.',
      url: 'https://github.com/microsoft',
      tags: ['mixed reality', 'ar'],
    ),
    AssetLibraryInfo(
      id: 'google_scanned',
      name: 'Google Scanned Objects Dataset',
      category: '🎲 3D Модели & Светове',
      exactCount: '1,030+ модела',
      countNumber: 1030,
      license: 'CC-BY 4.0',
      description: 'Реални битови предмети, сканирани с висока точност.',
      url: 'https://app.ignitionrobotics.org',
      tags: ['scanned', 'photogrammetry', 'physics'],
    ),
    AssetLibraryInfo(
      id: 'archive3d',
      name: 'Archive3D Public Architecture',
      category: '🎲 3D Модели & Светове',
      exactCount: '45,000+ модела',
      countNumber: 45000,
      license: 'Free Public',
      description: 'Мостове, кули, улични лампи, пейки и сгради.',
      url: 'https://archive3d.net',
      tags: ['city', 'bridges', 'street'],
    ),
    AssetLibraryInfo(
      id: 'hum3d_samples',
      name: 'Hum3D Vehicle Samples',
      category: '🎲 3D Модели & Светове',
      exactCount: '150+ модела',
      countNumber: 150,
      license: 'Free Samples Tier',
      description: 'Прецизни модели на спортни автомобили и камиони.',
      url: 'https://hum3d.com',
      tags: ['vehicles', 'cars', 'wheels'],
    ),

    // ==========================================
    // 🎨 2D СПРАЙТОВЕ & ПЛОЧКИ (24-40)
    // ==========================================
    AssetLibraryInfo(
      id: 'craftpix',
      name: 'CraftPix 2D Freebies',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '6,800+ спрайта',
      countNumber: 6800,
      license: 'Free Commercial',
      description: 'Пиксел арт рицари, чудовища, подземия, паралакс фонове и UI бутони.',
      url: 'https://craftpix.net',
      tags: ['pixel art', 'knights', 'monsters', 'rpg'],
    ),
    AssetLibraryInfo(
      id: 'kenney_2d',
      name: 'Kenney 2D Assets',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '8,500+ спрайта',
      countNumber: 8500,
      license: 'CC0 Public Domain',
      description: 'Платформинг плочки, Сокобан, роуглайк карти, интерфейсни елементи.',
      url: 'https://kenney.nl',
      tags: ['tileset', 'platformer', 'retro'],
    ),
    AssetLibraryInfo(
      id: 'opengameart_2d',
      name: 'OpenGameArt 2D Sprites',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '28,000+ спрайта',
      countNumber: 28000,
      license: 'CC0 / GPL',
      description: 'Спрайтшитове за герои с ходене, бой, скачане и магии.',
      url: 'https://opengameart.org',
      tags: ['spritesheets', 'animations'],
    ),
    AssetLibraryInfo(
      id: 'itch_io_free',
      name: 'Itch.io Free Game Assets',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '35,000+ пакета',
      countNumber: 35000,
      license: 'CC0 / Free',
      description: 'Инди пакети от хиляди независими пиксел арт автори.',
      url: 'https://itch.io',
      tags: ['indie', 'pixel art', 'packs'],
    ),
    AssetLibraryInfo(
      id: 'game_icons',
      name: 'Game-Icons.net Vector Library',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '4,120+ SVG/PNG',
      countNumber: 4120,
      license: 'CC-BY 3.0',
      description: 'Векторни икони за оръжия, щитове, заклинания, отвари и инвентари.',
      url: 'https://game-icons.net',
      tags: ['icons', 'rpg', 'spells', 'vector'],
    ),
    AssetLibraryInfo(
      id: 'glitch_archive',
      name: 'Glitch The Game Master Archive',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '10,000+ асета',
      countNumber: 10000,
      license: 'CC0 Public Domain',
      description: 'Пълният визуален свят на играта Glitch от създателите на Slack.',
      url: 'https://www.glitchthegame.com',
      tags: ['vector art', 'creatures', 'nature'],
    ),
    AssetLibraryInfo(
      id: 'lospec',
      name: 'Lospec Pixel Archive',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '1,800+ палитри',
      countNumber: 1800,
      license: 'CC0 / Open',
      description: 'Цветови палитри и плочки за класически игрови конзоли (GameBoy, NES).',
      url: 'https://lospec.com',
      tags: ['palettes', 'retro', '8-bit'],
    ),
    AssetLibraryInfo(
      id: 'superpowers_2d',
      name: 'Superpowers 2D Retro Packs',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '2,400+ спрайта',
      countNumber: 2400,
      license: 'CC0 Public Domain',
      description: 'Класически нинджи, космически изтребители и платформинг блокове.',
      url: 'https://github.com/sparklinlabs',
      tags: ['retro', 'arcade', 'spaceships'],
    ),
    AssetLibraryInfo(
      id: 'freegameassets_2d',
      name: 'FreeGameAssets 2D Collection',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '4,200+ спрайта',
      countNumber: 4200,
      license: 'Free Commercial',
      description: 'Фентъзи герои, чудовища, подземия и оръжия.',
      url: 'https://free-game-assets.itch.io',
      tags: ['monsters', 'chibi', 'tiles'],
    ),
    AssetLibraryInfo(
      id: 'reiners_tilesets',
      name: 'Reiner\'s Tilesets Archive',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '3,000+ спрайта',
      countNumber: 3000,
      license: 'Freeware / Open',
      description: 'Изометрични растения, замъци, животни и рицари.',
      url: 'https://reinerstilesets.de',
      tags: ['isometric', 'nature', 'animals'],
    ),
    AssetLibraryInfo(
      id: 'pipoya_vfx',
      name: 'Pipoya VFX 2D Effects',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '850+ анимации',
      countNumber: 850,
      license: 'Free Commercial',
      description: 'Пиксел арт ефекти за огън, лед, светкавици, експлозии и портали.',
      url: 'https://pipoya.itch.io',
      tags: ['vfx', 'fire', 'spells', 'particles'],
    ),
    AssetLibraryInfo(
      id: 'openclipart',
      name: 'OpenClipart Public Vectors',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '160,000+ SVG',
      countNumber: 160000,
      license: 'Public Domain',
      description: 'Векторни предмети, сгради, бутони и фонове.',
      url: 'https://openclipart.org',
      tags: ['svg', 'vector', 'illustrations'],
    ),
    AssetLibraryInfo(
      id: 'flaticon_gaming',
      name: 'Flaticon Gaming Free Icons',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '15,000+ икони',
      countNumber: 15000,
      license: 'Free Attribution',
      description: 'Модерни плоски икони за геймпади, сърца, монети и брони.',
      url: 'https://flaticon.com',
      tags: ['ui icons', 'badges'],
    ),
    AssetLibraryInfo(
      id: 'game_art_guru',
      name: '2D Game Art Guru Pack',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '300+ векторни комплекта',
      countNumber: 300,
      license: 'CC-BY',
      description: 'Модулни елементи за създаване на платформинг нива.',
      url: 'https://2dgameartguru.com',
      tags: ['modular 2d', 'vectors'],
    ),
    AssetLibraryInfo(
      id: 'zelda_classic',
      name: 'Zelda Classic Quest Tiles',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '5,000+ плочки',
      countNumber: 5000,
      license: 'Public Domain',
      description: 'Ретро плочки в стил 16-битови класики за приключенски светове.',
      url: 'https://www.purezc.net',
      tags: ['zelda-like', 'topdown', 'retro'],
    ),
    AssetLibraryInfo(
      id: 'lpc_sprites',
      name: 'Liberated Pixel Cup (LPC)',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '1,200+ спрайта',
      countNumber: 1200,
      license: 'CC-BY-SA 3.0 / GPL',
      description: 'Официална модулна база за пиксел арт с напълно съвместими тела и дрехи.',
      url: 'https://opengameart.org',
      tags: ['modular sprites', 'lpc', 'rpg'],
    ),
    AssetLibraryInfo(
      id: 'retro_game_zone',
      name: 'RetroGameZone Sprites',
      category: '🎨 2D Спрайтове & Плочки',
      exactCount: '2,000+ спрайта',
      countNumber: 2000,
      license: 'Open Access',
      description: 'Класически фонове и персонажи за аркадни платформи.',
      url: 'https://retrogamezone.co.uk',
      tags: ['arcade', '16-bit'],
    ),

    // ==========================================
    // 🌋 PBR ТЕКСТУРИ & HDRIs (41-50)
    // ==========================================
    AssetLibraryInfo(
      id: 'poly_haven',
      name: 'Poly Haven (Texture & HDRI Haven)',
      category: '🌋 PBR Текстури & HDRIs',
      exactCount: '1,350+ 4K асета',
      countNumber: 1350,
      license: 'CC0 Public Domain',
      description: 'Златният стандарт за фотореалистични PBR материали и 360° небесни панорами.',
      url: 'https://polyhaven.com',
      tags: ['pbr', 'hdri', 'skybox', 'photogrammetry'],
    ),
    AssetLibraryInfo(
      id: 'ambient_cg',
      name: 'AmbientCG Scanned Surfaces',
      category: '🌋 PBR Текстури & HDRIs',
      exactCount: '2,200+ PBR материала',
      countNumber: 2200,
      license: 'CC0 Public Domain',
      description: 'Сканиран асфалт, вряща лава, скали, ръжда, плочки, мрамор и бетон.',
      url: 'https://ambientcg.com',
      tags: ['seamless', '4k textures', 'normal maps'],
    ),
    AssetLibraryInfo(
      id: 'share_textures',
      name: 'ShareTextures CC0 Repository',
      category: '🌋 PBR Текстури & HDRIs',
      exactCount: '1,400+ текстури',
      countNumber: 1400,
      license: 'CC0 Public Domain',
      description: 'Строителни материали, дърво, тухлени стени, пясък и сняг.',
      url: 'https://sharetextures.com',
      tags: ['bricks', 'wood', 'ground'],
    ),
    AssetLibraryInfo(
      id: 'cg_bookcase',
      name: 'CGBookcase PBR Textures',
      category: '🌋 PBR Текстури & HDRIs',
      exactCount: '600+ текстури',
      countNumber: 600,
      license: 'CC0 Public Domain',
      description: 'Високодетайлни PBR карти до 4K за Unreal и Unity.',
      url: 'https://cgbookcase.com',
      tags: ['roughness', 'metalness', 'displacement'],
    ),
    AssetLibraryInfo(
      id: 'texture_can',
      name: 'TextureCan PBR Sets',
      category: '🌋 PBR Текстури & HDRIs',
      exactCount: '550+ комплекта',
      countNumber: 550,
      license: 'CC0 Public Domain',
      description: 'Процедурно създадени безшевни текстури за гейминг.',
      url: 'https://texturecan.com',
      tags: ['procedural', 'patterns'],
    ),
    AssetLibraryInfo(
      id: 'three_d_assets_one',
      name: '3DAssets.one Search Engine',
      category: '🌋 PBR Текстури & HDRIs',
      exactCount: 'Индекс на 18 сайта',
      countNumber: 15000,
      license: 'CC0 Search Meta',
      description: 'Метатърсачка, обединяваща хиляди отворени 3D текстури.',
      url: 'https://3dassets.one',
      tags: ['search engine', 'aggregator'],
    ),
    AssetLibraryInfo(
      id: 'public_domain_textures',
      name: 'Public Domain Textures',
      category: '🌋 PBR Текстури & HDRIs',
      exactCount: '350+ фотоскана',
      countNumber: 350,
      license: 'CC0 Public Domain',
      description: 'Истински сканирани природни повърхности.',
      url: 'https://publicdomaintextures.com',
      tags: ['nature', 'moss', 'bark'],
    ),
    AssetLibraryInfo(
      id: 'textures_com_free',
      name: 'Textures.com Free Section',
      category: '🌋 PBR Текстури & HDRIs',
      exactCount: '2,000+ текстури',
      countNumber: 2000,
      license: 'Free Daily Quota',
      description: 'Текстури за врати, прозорци, сгради и метал.',
      url: 'https://textures.com',
      tags: ['decals', 'doors', 'windows'],
    ),
    AssetLibraryInfo(
      id: 'hdri_hub',
      name: 'HDRI-Hub Free Panoramas',
      category: '🌋 PBR Текстури & HDRIs',
      exactCount: '80+ панорами',
      countNumber: 80,
      license: 'Free Samples',
      description: '360° дневни и нощни небеса за реалистично осветление.',
      url: 'https://hdri-hub.com',
      tags: ['lighting', 'sky'],
    ),
    AssetLibraryInfo(
      id: 'free_pbr',
      name: 'FreePBR Materials',
      category: '🌋 PBR Текстури & HDRIs',
      exactCount: '120+ материала',
      countNumber: 120,
      license: 'Free Commercial',
      description: 'Оптимизирани материали за бърз мобилен рендеринг.',
      url: 'https://freepbr.com',
      tags: ['mobile friendly', 'substances'],
    ),
  ];
}
