name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clean Android & Remove tests
        run: |
          rm -rf android
          flutter create . --platforms=android --org com.stanbg96.tiptop --project-name tiptop_game_engine
          rm -rf test

      - name: Install dependencies
        run: flutter pub get

      - name: 🔍 Извличане САМО на критичните грешки
        run: |
          flutter analyze > analyze_log.txt 2>&1 || true
          echo "==============================================="
          echo "ТОЧНИ КРИТИЧНИ ГРЕШКИ (АКО ИМА):"
          grep -E "error •" analyze_log.txt || echo "Няма критични грешки! Всичко е само info."
          echo "==============================================="

      - name: 🚀 Компилиране на APK (Release)
        run: flutter build apk --release

      - name: 📦 Качване на готовия APK
        uses: actions/upload-artifact@v4
        with:
          name: TipTop-Game-Engine-APK
          path: build/app/outputs/flutter-apk/app-release.apk
